env = Environment();
env = Environment();

env['CXX'] = '/opt/local/bin/g++-mp-4.5';

env.AppendUnique(CPPFLAGS = ['-std=c++0x']);
env.AppendUnique(CPPFLAGS = ['-g']);
#env.AppendUnique(CPPFLAGS = ['-O3']);

env.AppendUnique(CPPPATH = [
	'/usr/local/include/boost_1_45_0',
	'/Users/bracket/src/rasterizer',
]);

env.AppendUnique(LIBS = ['libboost_unit_test_framework.dylib']);

sources = [
	'test_suite.cpp',
	'../RationalBilinearInverter.cpp',
];

env.Program('test_suite', sources);
